### ISSUE TITLE
Bug with our Magento 2.4.2 install and Amasty One Step Checkout

### ISSUE THREAD

**Issue by angelflo** [COINQVEST/magento-2-extension#3]
Hi,
I tried to install your extension in order to use it for our customers on magento 2.4.2 stable release with One Step Checkout extension but when I enable your extension it crash our checkout process (impossible to valide the order with validate order button)

In the chrome console I  saw an error message : 
![2021-03-03_14-34-30](https://user-images.githubusercontent.com/9958770/109815244-b52f1180-7c2f-11eb-8f36-cc94500935aa.png)

I had currently disable your extension to restore something who work ... i'm not dev expert so if you have suggestion to solve this bug... and if not i'll try other company extension.

Thanks a lot

**Comment by anexgo** [comment]
Hi there,
Thanks for reaching out, we assume that this bug happens in combination with the One Page Checkout extension. Could you kindly share the extension source code & files, so we can replicate this issue on our test installation?
Appreciate your help!

**Comment by angelflo** [comment]
Hi,
Thanks a lot for your prompt reply and to investigate on this issue.
Please can you give me an email where i can share with you the last version on Amasty OSC (I can't share it here in public mode)
Kind regards,Florent

**Comment by anexgo** [comment]
Hi Florent,
Great, please send it to service@coinqvest.com.
Thanks, Stefan

**Comment by anexgo** [comment]
Hi Florent,
I sent you a patch by email. Please let me know if that works out.
Stefan
